export enum CreditStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  DISBURSED = "DISBURSED",
  REPAYING = "REPAYING",
  COMPLETED = "COMPLETED",
  DEFAULTED = "DEFAULTED",
}
